function [] = clean_launch_vehicle_selections()

jess defrule CLEAN::clean-LVs ...
    (declare (salience 30)) ...
    ?orig <- (MANIFEST::Mission (launch-vehicle ?lv&~nil)) ...
    => ...
    (modify ?orig (launch-vehicle nil) (launch-cost# 0));
jess focus CLEAN;
jess run;
end
