%this function extracts specified features from the data set generated by
%mergePopulations.m It is assumed that the data set is contained in a
%variable labeled "decisions" and is an (m,n) matrix where m is the number
%of observations and n is the number of decision variables
%
%features
%   numSatellites
%   instruments
%   orbits
 
 
 
path = '/Users/nozomihitomi/Dropbox/EOSS/problems/climateCentric/result/ASC Paper/analysis/pop_all/';
load(strcat(path,'for Ref Pop allPop.mat'));
 
%data size
ndata = size(decisions,1);
 
%5 satellites
maxNumSats = 5;
%12 instruments
maxNumInst = 12;
instName = {'ACE_ORCA','ACE_POL','ACE_LID','CLAR_ERB',...
    'ACE_CPR','DESD_SAR','DESD_LID','GACM_VIS',...
    'GACM_SWIR','HYSP_TIR','POSTEPS_IRS','CNES_KaRIN'};
%12 orbits
maxNumOrb = 12;
orbName = {'400-polar','400-sso-am','400-sso-pm','400-sso-dd','600-polar','600-sso-am','600-sso-pm','600-sso-dd','800-polar','800-sso-am','800-sso-pm','800-sso-dd'};
 
%logical indices of instrument assignment
ind_inst = zeros(maxNumSats,maxNumSats * maxNumInst + maxNumSats);
for i=1:maxNumSats
    ind_inst(i,(i-1)*(maxNumInst + 1) + 1:i*(maxNumInst + 1) - 1) = true;
end
ind_inst = logical(ind_inst);
 
%logical indices of the orbit assignment
ind_orb = zeros(maxNumSats,maxNumSats * maxNumInst + maxNumSats);
for i=1:maxNumSats
    ind_orb(i,i*(maxNumInst +1)) = true;
end
ind_orb = logical(ind_orb);
 
%number of copies of each intrument in each architecture
copyInstPerArch = zeros(ndata,maxNumInst);
for i=1:maxNumSats
    copyInstPerArch = copyInstPerArch + decisions(:,ind_inst(i,:));
end
 
%number of instruments per satellite
numInstPerSat = zeros(ndata,maxNumSats);
for i=1:maxNumSats
    sat_i = decisions(:,ind_inst(i,:));
    numInstPerSat(:,i) = sum(sat_i,2);
end
 
%On off satellites
satsOnOff = dutyCycle > 0;
nSatsOn = sum(satsOnOff,2);
 
%number of instruments per architecture
numInstPerArch = sum(numInstPerSat,2);
 
%boolean for if satellite carries any instruments
bool_sat = numInstPerSat > 0;
 
%numSatellites
numSatellites = sum(bool_sat,2);
 
%orbits (modify orbit selection id to mean 0 = no satellite occupying that
%orbit)
orbit = zeros(ndata,maxNumSats);
for i=1:maxNumSats
    modifiedOrbitNumber = decisions(:,ind_orb(i,:)) + 1;
    modifiedOrbitNumber(~bool_sat(:,i)) = 0;
    orbit(:,i) = modifiedOrbitNumber;
end
 
%copies of orbits
orbit_copy = zeros(ndata,maxNumOrb);
for i=1:maxNumOrb
    orbit_copy(:,i) = sum(orbit == i,2);
end
 
%copies of orbits at specific altitudes:
alt_400 = sum(orbit_copy(:,1:4),2);
alt_600 = sum(orbit_copy(:,5:8),2);
alt_800 = sum(orbit_copy(:,9:12),2);
 
%copies of orbits at specific RAAN:
raan_polar = sum(orbit_copy(:,1:4:maxNumOrb),2);
raan_sso_am = sum(orbit_copy(:,2:4:maxNumOrb),2);
raan_sso_pm = sum(orbit_copy(:,3:4:maxNumOrb),2);
raan_sso_dd = sum(orbit_copy(:,4:4:maxNumOrb),2);
 
%find optimal instrument to orbit assignments
pointingInsts = [5,6,12];
atmInsts = [9];
opticalInsts = [1,2,3,4,6,7,8,9,10,11];
orbitdd = [3, 7, 11];
orbitpm = [4, 8, 12];
orbit400 = [1:4];
opt_inst_orb = zeros(ndata,maxNumSats);
for i=1:maxNumSats
    sat_i = decisions(:,ind_inst(i,:));
    hasPointing = any(sat_i(:,pointingInsts),2);
    hasAtm = any(sat_i(:,atmInsts),2);
    hasOptical = any(sat_i(:,opticalInsts),2);
    fliesInDD = ismember(orbit(:,i),orbitdd);
    fliesInPM = ismember(orbit(:,i),orbitpm);
    fliesIn400 = ismember(orbit(:,i),orbit400);
     
    optPointing = and(hasPointing, not(fliesIn400));
    optAtm = and(hasAtm, fliesInPM);
    optOptical = and(hasOptical, not(fliesInDD));
     
    opt_inst_orb(:,i) = optPointing + optAtm + optOptical;
end
 
%find synergy occurences
synergyPairs = [1,2;    %ace_orca, ace_pol
                1,3;    %ace_orca, ace_lid
                1,7;    %ace_orca, desd_lid
                1,8;    %ace_orca, gacm_vis
                1,10;   %ace_orca, hysp_tir
                2,7;    %ace_pol, desd_lid
                3,7;    %ace_lid, desd_lid
                3,8;    %ace_lid, gacm_vis
                3,12;   %ace_lid, cnes_karin
                10,11]; %hysp_tir, posteps_irs
synergylabel = {'ace_orca, ace_pol','ace_orca, ace_lid','ace_orca, desd_lid',...
    'ace_orca, gacm_vis','ace_orca, hysp_tir','ace_pol, desd_lid','ace_lid, desd_lid',...
     'ace_lid, gacm_vis','ace_lid, cnes_karin','hysp_tir, posteps_irs'};
synergyPairCount = zeros(size(decisions,1),size(synergyPairs,1));
for i=1:maxNumSats
    satInst = decisions(:,ind_inst(i,:));
    for j=1:size(synergyPairs,1)
        synergyPairCount(:,j) = synergyPairCount(:,j) + sum(satInst(:,synergyPairs(j,:)),2)==2;
    end
end
             
%plot the number of instruments and satellites in the architecture
figure(1)
scatter(-objectives(:,1),objectives(:,2),5,numSatellites)    
colormap jet
colorbar
title('Number of sats in arch')
figure(2)
scatter(-objectives(:,1),objectives(:,2),5,numInstPerArch)    
colormap jet
colorbar
title('Number of inst per arch')
figure(3)
scatter(-objectives(:,1),objectives(:,2),5,mean(numInstPerSat,2))    
colormap jet
colorbar
title('Avg. Num. of inst per sat')
 
%plot the number of instrument copies in the architecture
figure(4)
for i=1:maxNumInst
    subplot(3,4,i)
    scatter(-objectives(:,1),objectives(:,2),5,copyInstPerArch(:,i))
    title(instName{i})
    colormap jet
    colorbar
end
figure(5)
bar(sum(copyInstPerArch,1));
h = gca;
h.XTickLabel = instName;
h.XTickLabelRotation = 90;
 
 
%plot the number of orbit copies in the architecture
figure(6)
for i=1:maxNumOrb
    subplot(3,4,i)
    scatter(-objectives(:,1),objectives(:,2),5,orbit_copy(:,i))
    title(orbName{i})
    colormap jet
    colorbar
end
figure(7)
bar(sum(orbit_copy,1));
h = gca;
h.XTickLabel = orbName;
h.XTickLabelRotation = 90;
 
%plot the number of synergies in each architecture
figure(8)
for i=1:length(synergylabel)
    subplot(2,5,i)
    scatter(-objectives(:,1),objectives(:,2),5,synergyPairCount(:,i))
    title(synergylabel{i})
    colormap jet
    colorbar
end
figure(9)
bar(sum(synergyPairCount,1));
h = gca;
h.XTickLabel = synergylabel;
h.XTickLabelRotation = 90;
 
%plot the heatmap of the duty cycle
figure(10)
subplot(3,2,1)
ind = dutyCycle > 1;
dutyCycle(ind) = 1;
meanDC = sum(dutyCycle,2)./numSatellites;
scatter(-objectives(:,1),objectives(:,2),5,meanDC)
colormap jet
colorbar
title('mean duty cycle')
%plot the heatmap of the number of optimal assignments of inst to orb
subplot(3,2,2)
scatter(-objectives(:,1),objectives(:,2),5,sum(opt_inst_orb,2))
colormap jet
colorbar
title('number of optimal instrument-orbit relationships')
%plot the heatmap of the number of interference pairs
subplot(3,2,3)
scatter(-objectives(:,1),objectives(:,2),5,interference)
colormap jet
colorbar
title('number of interference pairs')
%plot the heatmap of the mass
subplot(3,2,4)
scatter(-objectives(:,1),objectives(:,2),5,sum(mass,2)./numSatellites)
colormap jet
colorbar
title('mean mass')
%plot the heatmap of the packing efficiency
subplot(3,2,5)
ind = isnan(packingEfficiency);
packingEfficiency(ind) = 0;
scatter(-objectives(:,1),objectives(:,2),5,sum(packingEfficiency,2)./numSatellites)
colormap jet
colorbar
title('mean packing efficiency')
%plot the heatmap of the number of synergy pairs
subplot(3,2,6)
scatter(-objectives(:,1),objectives(:,2),5,sum(synergyPairCount,2))
colormap jet
colorbar
title('number of synergy pairs')