function [] = define_property(name, varargin)
% name, ...: string
% LHS has to set the design fact into ?sys, and either LHS or RHS has to
% bind the property value into the variable "?<name>".
%
% Example call:
% define_property Cost...
%     ?sys <- (logical (bat-subsys (pack ?bat) (series ?s) (parallel ?p)))...
%     (PART::Cost ?bat ?c)...
%     =>...
%     (bind ?Cost (* ?s ?p ?c));
    
    %%
    
    body = varargin;
    
    % If there's no RHS, add the arrow to the end of the body:
    if ~any(cellfun(@(str) strcmp(str, '=>'), body))
        body = [body {'=>'}];
    end
    
    jess({...
        'defrule' ['calc-' name] ...
            '(declare (salience 100))' ...
            body ...
            '(assert (' name '?sys' ['?' name] '))'...
        });
        
    jess({...
        'defquery' ['query-' name] ...
            '(declare (variables ?sys))' ...
            '(' name '?sys ?value $?)'...
        });
end