function [] = define_constraint(name, varargin)
% DEFINE_CONSTRAINT: name, varargin: string;
% LHS has to set the design fact into ?sys.
%
% Example call:
%     define_constraint not-enough-v...
%         ?sys <- (bat-subsys (series ?ns))...
%         (Voltage ?sys ?v & :(< ?v 10))...
%         =>...
%         (duplicate ?sys (series (+ 1 ?ns)));... try more series
    
    body = varargin;
    
    % If there's no RHS, add the arrow to the end of the body:
    if ~any(cellfun(@(str) strcmp(str, '=>'), body))
        body = [body {'=>'}];
    end
    
    jess([...
        'defrule constraint-' name ' '...
            '(declare (salience 200)) '...
            cat_with_spaces(body{:})...
            '(retract ?sys)'...
            ]);
end